services:
  admin-app:
    image: jeanleonkabobi/admin-app:0.0.1
    container_name: container_admin-app
    environment:
      DB_HOST: mysql-admin-db
      DB_NAME: adminapp-db
      DB_USERNAME: user
      DB_PASSWORD: user123
    ports:
      - "8081:8080"
    depends_on:
      mysql-admin-db:
        condition: service_healthy
      redis:
        condition: service_started

  mysql-admin-db:
    image: mysql:8.0
    container_name: container_mysql-admin-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adminapp-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
    volumes:
      - admin_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=user123"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:5.0.3-alpine
    container_name: admin-app-redis
    ports:
      - "6379:6379"

volumes:
  admin_mysql_data:
    driver: local